services:
  - type: web
    name: prombarjin-enterprise-x
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
